FreeTAKServer-UI/app/base/models.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask_login import UserMixin
from sqlalchemy import Binary, Column, Integer, String

from app import db, login_manager

from app.base.util import hash_pass

class User(db.Model, UserMixin):
    __tablename__ = 'user'
    uid = Column(String(25))
    id = Column(Integer, primary_key=True, autoincrement=True)
    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            setattr(self, property, value)

    def get_id(self):
        return self.uid

    def __repr__(self):
        return str(self.uid)


@login_manager.user_loader
def user_loader(uid):
    return User.query.filter_by(uid=uid).first()

@login_manager.request_loader
def request_loader(request):
    username = request.form.get('uid')
    user = User.query.filter_by(uid=username).first()
    return user if user else None

FreeTAKServer-UI/app/base/forms.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField
from wtforms.validators import InputRequired, Email, DataRequired

## login and registration

class LoginForm(FlaskForm):
    username = TextField    ('Username', id='username_login'   , validators=[DataRequired()])
    password = PasswordField('Password', id='pwd_login'        , validators=[DataRequired()])

class CreateAccountForm(FlaskForm):
    username = TextField('Username'     , id='username_create' , validators=[DataRequired()])
    # email    = TextField('Email'        , id='email_create'    , validators=[DataRequired(), Email()])
    password = PasswordField('Password' , id='pwd_create'      , validators=[DataRequired()])

class UpdateAccountForm(FlaskForm):
    password = TextField('Password' , id='password'      , validators=[DataRequired()])
    group = TextField('Group', id='group_update')
    token = TextField('Token', id='token', validators=[DataRequired()])

FreeTAKServer-UI/app/base/__init__.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'base_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static'
)

FreeTAKServer-UI/app/base/routes.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask import jsonify, render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user
)

from app import db, login_manager
from app.base import blueprint
from app.base.forms import LoginForm, CreateAccountForm
from app.base.models import User
from flask import current_app as app
from app.base.util import verify_pass

@blueprint.route('/')
def route_default():
    return redirect(url_for('base_blueprint.login'))

@blueprint.route('/error-<error>')
def route_errors(error):
    return render_template('errors/{}.html'.format(error))

## Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:
        import requests
        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = requests.get(f"http://{app.config['IP']}:{app.config['PORT']}/AuthenticateUser", params={"username": username, "password": password}, headers={"Authorization": f"{app.config['APIKEY']}"})
        try:
            user = user.json()
        except:
            return render_template('login/login.html', msg='Wrong user or password', form=login_form)
        
        # Check the password
        if user:
            user = User(uid = user["uid"])
            db.session.add(user)
            db.session.commit()
            login_user(user)
            z = current_user
            url = url_for('base_blueprint.route_default')
            new_redr = redirect(url)
            return new_redr

        # Something (user or pass) is not ok
        return render_template( 'login/login.html', msg='Wrong user or password', form=login_form)
    z = current_user
    if not current_user.is_authenticated:
        return render_template( 'login/login.html',
                                form=login_form)
    return redirect(url_for('home_blueprint.index'))

@blueprint.route('/logout')
def logout():
    db.session.delete(current_user)
    db.session.commit()
    logout_user()

    return redirect(url_for('base_blueprint.login'))

@blueprint.route('/shutdown')
def shutdown():
    func = request.environ.get('werkzeug.server.shutdown')
    if func is None:
        raise RuntimeError('Not running with the Werkzeug Server')
    func()
    return 'Server shutting down...'

## Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('errors/403.html'), 403

@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('errors/403.html'), 403

@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('errors/404.html'), 404

@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('errors/500.html'), 500

FreeTAKServer-UI/app/base/templates/base-site-rtl.html
<!--
=========================================================
* * Black Dashboard - v1.0.1
=========================================================

* Product Page: https://www.creative-tim.com/product/black-dashboard
* Copyright 2019 Creative Tim (https://www.creative-tim.com)


* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="/static/assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="/static/assets/img/favicon.png">
  <title>
    Flask Dashboard Black - {% block title %}{% endblock %} | AppSeed
  </title>
  <!--     Fonts and icons     -->
  <link href="/static/assets/css/css.css" rel="stylesheet" />
  <link href="/static/assets/css/all.css" rel="stylesheet" />
  <!-- Nucleo Icons -->
  <link href="/static/assets/css/nucleo-icons.css" rel="stylesheet" />
  <!-- CSS Files -->
  <link href="/static/assets/css/black-dashboard.css?v=1.0.0" rel="stylesheet" />
  <link href="/static/assets/css/bootstrap-rtl.css" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="/static/assets/demo/demo.css" rel="stylesheet" />

  <!-- Specific Page CSS goes HERE  -->
  {% block stylesheets %}{% endblock stylesheets %}

</head>

<body class="rtl menu-on-right ">
  <div class="wrapper">

    {% include 'site_template/sidebar-rtl.html' %}

    <div class="main-panel">

      {% include 'site_template/navigation-rtl.html' %}

      <div class="content">

        {% block content %}{% endblock content %}

      </div>

      {% include 'site_template/footer.html' %}

    </div>
    
  </div>

  {% include 'site_template/fixed-plugin.html' %}

  {% include 'site_template/scripts.html' %}

  {% include 'site_template/scripts-sidebar.html' %}

  <!-- Specific Page JS goes HERE  -->
  {% block javascripts %}{% endblock javascripts %}

</body>

</html>

FreeTAKServer-UI/app/base/templates/base-site.html
<!--
=========================================================
* * Black Dashboard - v1.0.1
=========================================================

* Product Page: https://www.creative-tim.com/product/black-dashboard
* Copyright 2019 Creative Tim (https://www.creative-tim.com)


* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
		<link rel="apple-touch-icon" sizes="76x76" href="/static/assets/img/apple-icon.png" />
		<link rel="icon" type="image/png" href="/static/assets/img/favicon.png" />
		<title>FreeTakServer - {% block title %}{% endblock %}</title>
		<!--     Fonts and icons     -->
		<link href="/static/assets/css/css.css" rel="stylesheet" />
		<link href="/static/assets/css/all.css" rel="stylesheet" />
		<!-- Nucleo Icons -->
		<link href="/static/assets/css/nucleo-icons.css" rel="stylesheet" />
		<!-- CSS Files -->
		<link href="/static/assets/css/black-dashboard.css?v=1.0.10" rel="stylesheet" />
		<script src="/static/assets/js/socket.io-1.4.5.js"></script>
		<script>
			document.write('<link href="/static/assets/css/jarvis.css?r=' + Math.floor(Math.random() * 100) + '" rel="stylesheet" type="text/css" />');
			document.write('<link href="/static/assets/css/jarvis_red.css?r=' + Math.floor(Math.random() * 100) + '" rel="stylesheet" type="text/css" />');
			document.write('<link href="/static/assets/css/jarvis_grey.css?r=' + Math.floor(Math.random() * 100) + '" rel="stylesheet" type="text/css" />');
			document.write('<link href="/static/assets/css/global.css?r=' + Math.floor(Math.random() * 100) + '" rel="stylesheet" type="text/css" />');
		</script>

		<!-- CSS Just for demo purpose, don't include it in your project -->
		<link href="/static/assets/demo/demo.css" rel="stylesheet" />

		<!-- Specific Page CSS goes HERE  -->
		{% block stylesheets %}{% endblock stylesheets %}
	</head>

	<body class="">
		<div class="wrapper">
			{% include 'site_template/sidebar.html' %}

			<div class="main-panel">
				{% include 'site_template/navigation.html' %}

				<div class="content">{% block content %}{% endblock content %}</div>

				{% include 'site_template/footer.html' %}
			</div>
		</div>

		{% include 'site_template/scripts.html' %} {% include 'site_template/scripts-sidebar.html' %}

		<!-- Specific Page JS goes HERE  -->
		{% block javascripts %} {% endblock javascripts %}
	</body>
</html>

FreeTAKServer-UI/app/base/templates/login/login.html
{% extends "base-site.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

        <div class="row">
          <div class="col-md-8">
            <div class="card">

              <form role="form" method="post" action="">
              
                {{ form.hidden_tag() }} 

                <div class="card-header">
                  <h3 class="title" style="color: #278aed;">[LOGIN]</h3>

                  <h6 class="card-category">
                      {% if msg %}
                        <span class="text-danger">{{ msg | safe }}</span>
                      {% else %}
                      <span style="font-size: 14px;">
                        Welcome to FTS administration, please insert you credential
                       
                      </span>
                      {% endif %}  
                  </h6>
                </div>

                <div class="card-body">

                    <div class="row">

                      <div class="col-md-3 px-md-1" >
                        <div class="form-group" style="padding: 0px 16px;">
                          <label>Username</label>
                          {{ form.username(class="form-control") }}
                        </div>
                      </div>

                    </div>
                    <div class="row">

                      <div class="col-md-3 px-md-1" >
                        <div class="form-group" style="padding: 0px 16px;">
                          <label>Password</label>
                          {{ form.password(class="form-control", type="password") }}
                        </div>
                      </div>

                    </div>
                    
                </div>
                <div class="card-footer">
                  <button type="submit" name="login" class="btn btn-primary">Login</button>
                  &nbsp; &nbsp;
                </div>

              </form>

            </div>
          </div>
      </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <script>
    $(document).ready(function() {
      // Javascript method's body can be found in assets/js/demos.js
      demo.initDashboardPageCharts();

    });
  </script>

{% endblock javascripts %}

FreeTAKServer-UI/app/base/templates/login/register.html
{% extends "base-site.html" %}

{% block title %} Register {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

        <div class="row">
          <div class="col-md-8">
            <div class="card">

              <form role="form" method="post" action="">
              
                {{ form.hidden_tag() }} 

                <div class="card-header">
                  <h5 class="title">Register</h5>

                  <h6 class="card-category">
                      {% if msg %}
                        <span class="text-danger">{{ msg | safe }}</span>
                      {% else %}
                        Complete your credentials
                      {% endif %}  
                  </h6>
                </div>

                <div class="card-body">

                    <div class="row">
                      <div class="col-md-3 px-md-1">
                        <div class="form-group">
                          <label>Username</label>
                          {{ form.username(class="form-control") }}
                        </div>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-md-3 px-md-1">
                        <div class="form-group">
                          <label>Password</label>
                          {{ form.password(class="form-control", type="password") }}
                        </div>
                      </div>
                    </div>
                    
                </div>
                <div class="card-footer">
                  <button type="submit" name="register" class="btn btn-fill btn-primary">Register</button>
                  &nbsp; &nbsp;
                  Have an account? <a href={{ url_for('base_blueprint.login') }} class="text-primary">Login</a>
                </div>

              </form>

            </div>
          </div>
      </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

FreeTAKServer-UI/app/base/templates/site_template/fixed-plugin.html
  <div class="fixed-plugin">
    <div class="dropdown show-dropdown">
      <a href="#" data-toggle="dropdown">
        <i class="fa fa-cog fa-2x"> </i>
      </a>
      <ul class="dropdown-menu">
        <li class="header-title"> Sidebar Background</li>
        <li class="adjustments-line">
          <a href="javascript:void(0)" class="switch-trigger background-color">
            <div class="badge-colors text-center">
              <span class="badge filter badge-primary active" data-color="primary"></span>
              <span class="badge filter badge-info" data-color="blue"></span>
              <span class="badge filter badge-success" data-color="green"></span>
            </div>
            <div class="clearfix"></div>
          </a>
        </li>
        <li class="adjustments-line text-center color-change">
          <span class="color-label">LIGHT MODE</span>
          <span class="badge light-badge mr-2"></span>
          <span class="badge dark-badge ml-2"></span>
          <span class="color-label">DARK MODE</span>
        </li>
        <li class="button-container">
          <a href="https://www.creative-tim.com/product/black-dashboard" target="_blank" class="btn btn-primary btn-block btn-round">Download HTML</a>
          <a href="https://demos.creative-tim.com/black-dashboard/docs/1.0/getting-started/introduction.html" target="_blank" class="btn btn-default btn-block btn-round">
            UI Documentation
          </a>
        </li>
        <li class="header-title">Thank you for 95 shares!</li>
      </ul>

      <br />
    </div>
  </div>
  

FreeTAKServer-UI/app/base/templates/site_template/navigation-rtl.html
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle d-inline">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="javascript:void(0)">RTL</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse" id="navigation">
            <ul class="navbar-nav  mr-auto">
              <li class="search-bar input-group">
                <button class="btn btn-link" id="search-button" data-toggle="modal" data-target="#searchModal"><i class="tim-icons icon-zoom-split" ></i>
                  <span class="d-lg-none d-md-block">Search</span>
                </button>
              </li>
              <li class="dropdown nav-item">
                <a href="javascript:void(0)" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="notification d-none d-lg-block d-xl-block"></div>
                  <i class="tim-icons icon-sound-wave"></i>
                  <p class="d-lg-none">
                    Notifications
                  </p>
                </a>
                <ul class="dropdown-menu dropdown-menu-right dropdown-navbar">
                  <li class="nav-link"><a href="#" class="nav-item dropdown-item">Mike John responded to your email</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">You have 5 more tasks</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Your friend Michael is in town</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Another notification</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Another one</a></li>
                </ul>
              </li>
              <li class="dropdown nav-item">
                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="photo">
                    <img src="/static/assets/img/anime3.png" alt="Profile Photo">
                  </div>
                  <b class="caret d-none d-lg-block d-xl-block"></b>
                  <p class="d-lg-none">
                    Log out
                  </p>
                </a>
                <ul class="dropdown-menu dropdown-navbar">
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Profile</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Settings</a></li>
                  <li class="dropdown-divider"></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Log out</a></li>
                </ul>
              </li>
              <li class="separator d-lg-none"></li>
            </ul>
          </div>
        </div>
      </nav>
      <div class="modal modal-search fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="SEARCH">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <i class="tim-icons icon-simple-remove"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
      <!-- End Navbar -->

FreeTAKServer-UI/app/base/templates/site_template/navigation.html
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle d-inline">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="javascript:void(0)">&nbsp;</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse" id="navigation">

            {% if current_user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
              <li class="search-bar input-group">
              &nbsp;
              </li>
              <li class="dropdown nav-item" id="events-info">
                <a href="javascript:void(0)" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="notification d-none d-lg-block d-xl-block" id="notif" style="display: none;"></div>
                  <i class="tim-icons icon-sound-wave"></i>
                  <p class="d-lg-none">
                    Notifications
                  </p>
                </a>

              </li>
              <li class="dropdown nav-item">
                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="photo">
                    <i class="tim-icons icon-single-02"></i>
                  </div>
                  <b class="caret d-none d-lg-block d-xl-block"></b>
                  <p class="d-lg-none">
                    Log out
                  </p>
                </a>
                <ul class="dropdown-menu dropdown-navbar">
                  <li class="nav-link"><a href="/page-user" class="nav-item dropdown-item">Profile</a></li>
                  <li class="dropdown-divider"></li>
                  <li class="nav-link"><a href={{ url_for('base_blueprint.logout') }} class="nav-item dropdown-item">Log out</a></li>
                </ul>
              </li>
              <li class="separator d-lg-none"></li>
            </ul>
            {% endif %}

          </div>
        </div>
      </nav>
      <div class="modal modal-search fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
            &nbsp;
            </div>
          </div>
        </div>
      </div>
      <!-- End Navbar -->

      
      

   

FreeTAKServer-UI/app/base/templates/site_template/scripts-sidebar.html
  <script>
    $(document).ready(function() {
      $().ready(function() {
        $sidebar = $('.sidebar');
        $navbar = $('.navbar');
        $main_panel = $('.main-panel');

        $full_page = $('.full-page');

        $sidebar_responsive = $('body > .navbar-collapse');
        sidebar_mini_active = true;
        white_color = false;

        window_width = $(window).width();

        fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();



        $('.fixed-plugin a').click(function(event) {
          if ($(this).hasClass('switch-trigger')) {
            if (event.stopPropagation) {
              event.stopPropagation();
            } else if (window.event) {
              window.event.cancelBubble = true;
            }
          }
        });

        $('.fixed-plugin .background-color span').click(function() {
          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data', new_color);
          }

          if ($main_panel.length != 0) {
            $main_panel.attr('data', new_color);
          }

          if ($full_page.length != 0) {
            $full_page.attr('filter-color', new_color);
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.attr('data', new_color);
          }
        });

        $('.switch-sidebar-mini input').on("switchChange.bootstrapSwitch", function() {
          var $btn = $(this);

          if (sidebar_mini_active == true) {
            $('body').removeClass('sidebar-mini');
            sidebar_mini_active = false;
            blackDashboard.showSidebarMessage('Sidebar mini deactivated...');
          } else {
            $('body').addClass('sidebar-mini');
            sidebar_mini_active = true;
            blackDashboard.showSidebarMessage('Sidebar mini activated...');
          }

          // we simulate the window Resize so the charts will get updated in realtime.
          var simulateWindowResize = setInterval(function() {
            window.dispatchEvent(new Event('resize'));
          }, 180);

          // we stop the simulation of Window Resize after the animations are completed
          setTimeout(function() {
            clearInterval(simulateWindowResize);
          }, 1000);
        });

        $('.switch-change-color input').on("switchChange.bootstrapSwitch", function() {
          var $btn = $(this);

          if (white_color == true) {

            $('body').addClass('change-background');
            setTimeout(function() {
              $('body').removeClass('change-background');
              $('body').removeClass('white-content');
            }, 900);
            white_color = false;
          } else {

            $('body').addClass('change-background');
            setTimeout(function() {
              $('body').removeClass('change-background');
              $('body').addClass('white-content');
            }, 900);

            white_color = true;
          }


        });

        $('.light-badge').click(function() {
          $('body').addClass('white-content');
        });

        $('.dark-badge').click(function() {
          $('body').removeClass('white-content');
        });
      });
    });
  </script>
  

FreeTAKServer-UI/app/base/templates/site_template/scripts.html
<!--   Core JS Files   -->
<script src="/static/assets/js/core/jquery.min.js"></script>
<script src="/static/assets/js/core/popper.min.js"></script>
<script src="/static/assets/js/core/bootstrap.min.js"></script>
<script src="/static/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>

<!-- Chart JS -->
<script src="/static/assets/js/plugins/chartjs.min.js"></script>
<script src="/static/assets/js/apexcharts.js"></script>
<!--  Notifications Plugin    -->
<script src="/static/assets/js/plugins/bootstrap-notify.js"></script>
<!-- Control Center for Black Dashboard: parallax effects, scripts for the example pages etc -->
<script src="/static/assets/js/black-dashboard.min.js?v=1.0.16.15"></script>
<!-- Black Dashboard DEMO methods, don't include it in your project! -->
<script src="/static/assets/demo/demo.js?v=1.0.16.15"></script>
<script src="/static/assets/js/charts/apexcharts.js"></script>
<script src="/static/assets/js/moment/moment.min.js"></script>

FreeTAKServer-UI/app/base/templates/site_template/sidebar-rtl.html
    <div class="sidebar">
      <div class="sidebar-wrapper">
        <div class="logo">
          <a href="https://appseed.us/admin-dashboards/flask-dashboard-material-design" class="simple-text logo-mini">
            FD
          </a>
          <a href="https://appseed.us/admin-dashboards/flask-dashboard-material-design" class="simple-text logo-normal">
            Flask Dashboard
          </a>
        </div>

        {% if current_user.is_authenticated %}
        <ul class="nav">
          <li class="active ">
            <a href="/">
              <i class="tim-icons icon-chart-pie-36"></i>
              <p>لوحة القيادة</p>
            </a>
          </li>
          <li>
            <a href="/ui-icons">
              <i class="tim-icons icon-atom"></i>
              <p>الرموز</p>
            </a>
          </li>
          <li>
            <a href="/ui-maps">
              <i class="tim-icons icon-pin"></i>
              <p>خرائط</p>
            </a>
          </li>
          <li>
            <a href="/ui-notifications">
              <i class="tim-icons icon-bell-55"></i>
              <p>إخطارات</p>
            </a>
          </li>
          <li>
            <a href="/page-user">
              <i class="tim-icons icon-single-02"></i>
              <p>ملف تعريفي للمستخدم</p>
            </a>
          </li>
          <li>
            <a href="/ui-tables">
              <i class="tim-icons icon-puzzle-10"></i>
              <p>قائمة الجدول</p>
            </a>
          </li>
          <li>
            <a href="/ui-typography">
              <i class="tim-icons icon-align-center"></i>
              <p>طباعة</p>
            </a>
          </li>
          <li>
            <a href="/page-rtl-support">
              <i class="tim-icons icon-world"></i>
              <p>دعم RTL</p>
            </a>
          </li>
          <li class="active-pro">
            <a href="https://appseed.us/admin-dashboards/flask-dashboard-material-design">
              <i class="tim-icons icon-spaceship"></i>
              <p>See product</p>
            </a>
          </li>
        </ul>
        {% endif %}
        
      </div>
    </div>